apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flask-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "testdb"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: flask-app
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "testdb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      storageClassName: yc-network-hdd
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi